### PR TITLE
Move status and processing model to HTML

### LINKED ISSUE #153: Remove "Dependencies" section
Now the ReSpec support automatic cross linking, the Dependencies section is not needed anymore. 

This can help catch a bunch of bugs and layering violations and encourages closer collaboration with other specs.

### PR DESCRIPTION
**Pull request by noamr**
Closes #153 and #154

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/preload/pull/162.html" title="Last updated on Mar 28, 2022, 7:32 AM UTC (b61d4a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/preload/162/05e56af...b61d4a0.html" title="Last updated on Mar 28, 2022, 7:32 AM UTC (b61d4a0)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
@caribouW3 @achristensen07 - A while ago we talked about moving preload to CR before retiring the current spec.
As that didn't happen, and its processing model is now (also) defined in HTML, are you OK with this PR? Should we move the document's status to be a Note?

**Comment by caribouW3** [comment]
@yoavweiss I think we should use "Discontinued Draft" status (with no change to the document except SOTD). 
See https://www.w3.org/2021/Process-20211102/#abandon-draft

**Comment by noamr** [comment]
> @yoavweiss I think we should use "Discontinued Draft" status (with no change to the document except SOTD). See https://www.w3.org/2021/Process-20211102/#abandon-draft

Done, according to the link.

**Review by caribouW3 — APPROVED** [review]

**Comment by caribouW3** [comment]
The published document will be different, since the process requires that the content matches the previously published one. But having the discontinued wording in the editors' draft SOTD was still useful. Thank you!

**Pull request merged**
