### PR TITLE
Delay the load event for preload is defined in HTML

### LINKED ISSUE #147: "Delay the load event" should happen in HTML
As discussed in whatwg/html#5595 ... this spec talks about "MUST NOT delay the load event". However, that should be defined in the HTML spec, not in this spec.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #147

***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/preload/pull/152.html" title="Last updated on Jul 18, 2020, 5:29 AM UTC (5da4d3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/preload/152/8c3d2ca...marcoscaceres:5da4d3a.html" title="Last updated on Jul 18, 2020, 5:29 AM UTC (5da4d3a)">Diff</a>

***

### :boom: Error: connect ETIMEDOUT 128.30.52.89:443 :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 28, 2022, 9:28 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fmarcoscaceres%2Fpreload%2F5da4d3a0e1e10860d3675c2363daf3f25cc33668%2Findex.html%3FisPreview%3Dtrue)

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/preload%23152.)._
</details>

### CODE REVIEW

**Comment by yoavweiss** [comment]
https://html.spec.whatwg.org/#link-type-preload doesn't seem to actually define that.
https://html.spec.whatwg.org/#fetching-and-processing-a-resource-from-a-link-element says "Unless otherwise specified for a given rel keyword, the element must delay the load event...". I believe the bits removed by this PR are the ones which currently "specify otherwise". Is it defined elsewhere in HTML where I missed it?

**Comment by domfarolino** [comment]
I agree with Yoav. Sorry, when I [commented here](https://github.com/w3c/preload/issues/147#issuecomment-652024989) I read the title of the issue as indicating that we want preloads to block the load event (but of course that doesn't feel right).

Given this, I recommend landing this PR after one is made to the HTML Standard adding a line indicating that preloads to not delay the load event: https://html.spec.whatwg.org/multipage/links.html#link-type-preload. See the "rel-manifest" section of the spec for a good example.

**Comment by noamr** [comment]
I think we can proceed with this now?

**Comment by yoavweiss** [comment]
I could be wrong but my read of https://html.spec.whatwg.org/multipage/semantics.html#fetching-and-processing-a-resource-from-a-link-element:delay-the-load-event is that link's are defined to generally delay the load event, and I see nothing to the contrary for preloads. Do we need to define something like that? Or am I missing something?

**Comment by noamr** [comment]
> I could be wrong but my read of https://html.spec.whatwg.org/multipage/semantics.html#fetching-and-processing-a-resource-from-a-link-element:delay-the-load-event is that link's are defined to generally delay the load event, and I see nothing to the contrary for preloads. Do we need to define something like that? Or am I missing something?

No need to define anything and seems like there's a WPT for this. Closing, feel free to reopen if needed.

**Comment by noamr** [comment]
Reopening, I misunderstood the issue.

**Pull request closed without merging**
