### PR TITLE
Added feature detection example

### LINKED ISSUE #7: how to feature detect?
How do I feature test if a new browser supports `link rel=preload`?

### PR DESCRIPTION
**Pull request by yoavweiss**
Closes #7 

@igrigorik - Can you take a look?

### CODE REVIEW

**Comment by yoavweiss** [comment]
PRed the example in DOM. Will link to it from here once it's in.

**Comment by igrigorik** [comment]
Great, thanks!

**Comment by toddreifsteck** [comment]
LGTM

**Comment by igrigorik** [comment]
@yoavweiss what's the resolution here? are we going to drop in a non-normative note to link to the example?

**Comment by yoavweiss** [comment]
The example in DOM as [currently suggested](https://github.com/whatwg/dom/pull/144#issuecomment-171392054) may not be of great value to developers in my view.

So, we can link to an [external example](https://gist.github.com/yoavweiss/8490dabb3e0aa112fc74) and/or simply write a short blog post that would explain the use of `supports()`.

**Comment by igrigorik** [comment]
@yoavweiss let's add a non-normative note in the spec and link to the gist (which, btw, should probably be .html to get the syntax highlighting). Once you have a blog post you can link it from the gist as well.

**Comment by igrigorik** [comment]
@yoavweiss looks like the HTML spec PR landed, can we update this and resolve it? :)

**Comment by igrigorik** [comment]
Closing, resolved via https://github.com/w3c/preload/pull/52.

**Pull request closed without merging**
