### PR TITLE
imagesrcset and imagesizes mutations are appropriate times to obtain the resource

### PR DESCRIPTION
**Pull request by domfarolino**
WIP because it depends on the not-yet-merged: https://github.com/whatwg/html/pull/4048

***
<a href="https://pr-preview.s3.amazonaws.com/domfarolino/preload/pull/134.html" title="Last updated on Feb 27, 2019, 3:51 PM UTC (56ae284)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/preload/134/b7b3c18...domfarolino:56ae284.html" title="Last updated on Feb 27, 2019, 3:51 PM UTC (56ae284)">Diff</a>

### CODE REVIEW

**Review by yoavweiss — APPROVED** [review]
LGTM once the related HTML patch lands

**Comment by yoavweiss** [comment]
@domfarolino Can you join the WG as an invited expert to make the IPR bots happy and green?

**Comment by yoavweiss** [comment]
Also, logistically, I don't think we discussed which milestone these preload extensions should go to, so please hold off on landing them until we do, as we may want to branch off L1 before that happens.

**Comment by domfarolino** [comment]
Absolutely, I'd like to block the HTML PR on https://github.com/whatwg/html/pull/4031 anyways, as that refactors some of the link loading infra. RE invited-expert status, that sounds good :)

**Comment by domfarolino** [comment]
> so please hold off on landing them until we do, as we may want to branch off L1 before that happens.

Given this, is it alright that the HTML Standard changes have already landed? Sorry, this comment kind of slipped my mind when applying the finishing touches and landing the change.

I've updated this PR to reflect the current state of the HTML Standard - I think all should be well now.

**Comment by noamr** [comment]
This is all handled in HTML now.

**Pull request closed without merging**
