### PR TITLE
Define http/2 server push interaction

### LINKED ISSUE #38: Preload and Server Push
More of a heads-up than an issue --

It look like `Link: <...>; rel=preload` is getting traction as the way to indicate to a server (whether local or remote to the content, such as with a CDN) that it should push the indicated assets.

See:
- https://httpd.apache.org/docs/trunk/mod/mod_http2.html#h2push
- https://h2o.examp1e.net/configure/http2_directives.html

I _think_ this is the right thing to do based upon the semantics (although my first instinct was `prefetch`, and it appears to have been that of Jake as well: https://youtu.be/CSjL1lrNAx4?t=4m29s)

So, if you don't want `preload` to be used in this fashion, I'd suggest jumping up and down about it pretty soon.

### PR DESCRIPTION
**Pull request by igrigorik**
@mnot @kazuho @icing please review and sanity check.

Closes #38.

### CODE REVIEW

**Comment by igrigorik** [comment]
This may belong in a separate thread, but since we're on the topic of server push topic... 

I'm hearing a need to distinguish between "_may push_" and _"passthrough"_ when using `rel=preload`. Today every `rel=preload` is a candidate for server push, and the observation is that sometimes the origin / application emitting the preload directives might know better and/or may want to exclude certain assets from being eligible for server push, while still instructing the client to preload it.

One simple way to address this would be to allow an additional parameter on the `Link` definition, e.g. `Link: <https://example.com/other/styles.css>; rel=preload; as=style; nopush`, or some such. 

@kazuho @icing curious to hear your thoughts, since you've already implemented this in your servers.

**Comment by yoavweiss** [comment]
Regarding the PR, looks good. We may want to add more about the aspects of preload that aren't satisfied by push (can address third party content, can take cache & cookies into consideration, etc).

Regarding `nopush`, can you share specific use cases? Is it mainly for the "user probably has it in cache" case?

**Comment by dshafik** [comment]
@igrigorik I've been [a proponent](https://daveyshafik.com/archives/69603-http2-server-push-youre-doing-it-all-wrong.html) of splitting the two behaviors, having a `rel=push` to explicitly mark it as push. 

This header (if the server understands it) should never reach the client intact — instead, it should either be stripped when the resource is pushed, or perhaps optionally changed to `rel=preload` instead. 

It may also solve some potential race conditions between pushing and attempting to preload the same resource.

While in _most_ cases `rel=push` and `rel=preload` can — and will — be treated as one and the same; having the additional granularity, should you choose to use it, as we move forward into new HTTP architectures around H2 that we can't yet foresee could be very beneficial.

**Comment by igrigorik** [comment]
> Regarding nopush, can you share specific use cases? Is it mainly for the "user probably has it in cache" case?

Yes, exactly as you described: in cache + cookies use cases. For example, origin believes the user is likely to have the asset in cache already but wants to hedge its bet, or needs the client to initiate the request due to required scoped cookies or some such.

---

> @igrigorik I've been a proponent of splitting the two behaviors, having a rel=push to explicitly mark it as push. This header (if the server understands it) should never reach the client intact — instead, it should either be stripped when the resource is pushed, or perhaps optionally changed to rel=preload instead.

This approach has several problems: (1) it's not h1 friendly, (2) counting on upstream servers/proxies to strip or convert headers is a bad idea^(tm) and locks you into being behind a server that supports this functionality. By contrast, `preload` directive allows me to deploy my site on any server/upstream proxy regardless of whether it supports h2, h2+push, or only http/1.1, and still get a performance benefit. To get similar behavior with rel=push developers would be forced to duplicate same URLs in rel=push and rel=preload.

> It may also solve some potential race conditions between pushing and attempting to preload the same resource.

Deliver your PUSH_PROMISE's first. I don't believe preload creates any new race conditions.

That said, stepping back, what you're proposing here is push opt-in, whereas `nopush` is an opt-out strategy. FWIW, I think the latter is a better strategy due to reasons listed above.

**Comment by mnot** [comment]
Looks reasonable to me. This is a bit of a weird one, because the relationship between an origin server and a CDN or other reverse proxy is non-standard and effectively a private contract, so it's hard to talk about in standards.

**Comment by kazuho** [comment]
@igrigorik :+1: The description looks very clear to me.

Regarding `nopush`, I like the fact that it defines push indication (via the use of `Link` header) a proper subset of `rel=preload`.

As stated in your description, a pushed response is

> retained by the user agent and executed by the application when matched with another request initiated by the application.

Therefore, IMO a pushed resource should always be indicated with `link: rel=preload` header so that it would always find its place within the browser cache, even in case the content did not refer to the pushed resource (or in case the client failed to detect a reference to the pushed resource).  Introduction of `nopush` is consistent with this understanding.

**Comment by yoavweiss** [comment]
> To get similar behavior with rel=push developers would be forced to duplicate same URLs in rel=push and rel=preload.

Since `rel` can contain a list of relations, that's not necessary.

I think that whether we discuss `push` (an opt in) or `nopush` (an opt out), it would be cleaner if it was an extra `rel` (which browsers ignore) rather than a separate attribute. 

> Yes, exactly as you described: in cache + cookies use cases. For example, origin believes the user is likely to have the asset in cache already but wants to hedge its bet, or needs the client to initiate the request due to required scoped cookies or some such.

Regarding the "resource in cache" use case, I'm hoping [cache digests](https://mnot.github.io/I-D/h2-cache-digest/) would handle it eventually. The "we need the cookies" case however is here to stay, so we should definitely cover it.

**Comment by icing** [comment]
Proposed change works for me.

`rel=nopush` looks weird. I read relations as something that is, not as the absence of a thing. 

Given that we have shipped a default to push preloads, I'd prefer the explicit `nopush` notation. But I could be swayed to only push on seeing a `rel=push` param which, most often will appear as `rel="preload push"`.

While we are at this: Apache does not push preload headers from resources that are being pushed themselves. This is just to avoid downloading the internet. Hope that is fine with the intention of preload.

(Ultimately, but that goes beyond the scope of this thread, we try to describe the _optimal load strategy_ for a page and try to bring client and server state somehow together to realize this. I wonder how far Link and Cache-Digest header can take us, before we run into the UA-sniffing trap again.

It _is_ the client that knows best what it needs and when, not the server or the webapp or an intermediary. Clients like `curl` probably will never enable PUSH by default just to avoid getting overwhelmed by css and images it has no use for.

If instead, we had some kind of load strategy document, a short, complete description of resource relations for a page, pushing that might work better for everyone.)

**Comment by vkrasnov** [comment]
I am all for the nopush behavior.

I would also like to add that delivering the promises first is a performance killer. There are cases when there are dozens of promises to send, and it increases TTFB.
That beats the purpose of push as a performance feature.

How about adding a 'willpush' behaviour, that tells that a push primise will follow after the data, eliminating the race condition.

**Comment by sheronz** [comment]
@igrigorik How can an origin / CDN can do "smart bet"  whether a resource is not in the client's cache and should be pushed to it?

**Comment by igrigorik** [comment]
Thanks everyone for great feedback!

> @yoavweiss: Since rel can contain a list of relations, that's not necessary. I think that whether we discuss push (an opt in) or nopush (an opt out), it would be cleaner if it was an extra rel (which browsers ignore) rather than a separate attribute.

Browsers will similarly ignore the attribute. My argument against opt-in is that this will quickly lead to _"always specify `rel='preload push'`"_ pattern across the web, which is entirely unnecessary. Functionally, a pushed resource behaves the same on the client as a preloaded one; push is a latency optimization on preload; every preload resource should be a candidate for push, unless there is explicit opt-out.

> @icing: While we are at this: Apache does not push preload headers from resources that are being pushed themselves. This is just to avoid downloading the internet. Hope that is fine with the intention of preload.

I think this is fine, modulo one nuance... Current implementations of push in Chrome+FF do not commit the resource to HTTP cache until it is matched by a client request. Preload resources, on the other hand, are committed to HTTP cache, since they're 'client-initiated'. As such, pushing a preload request + stripping the header changes the behavior a bit... This is gray (unspecified) area, and something we should probably define more formally.

> @icing: If instead, we had some kind of load strategy document, a short, complete description of resource relations for a page, pushing that might work better for everyone.

Kinda, sorta this: https://github.com/GoogleChrome/http2-push-manifest - might be worth exploring.

> @vkrasnov: I would also like to add that delivering the promises first is a performance killer. There are cases when there are dozens of promises to send, and it increases TTFB. That beats the purpose of push as a performance feature. How about adding a 'willpush' behaviour, that tells that a push primise will follow after the data, eliminating the race condition.

`willpush` is a promise. :) The overhead of a `PUSH_PROMISE` is ~10~20 bytes, is that really a problem in practice? If we're delivering a large number of `rel=preloads` in the `HEADERS` frame, we're ~equally delaying the content TTFB. 

> @sheronz: How can an origin / CDN can do "smart bet" whether a resource is not in the client's cache and should be pushed to it?

[Cache-digests](https://datatracker.ietf.org/doc/draft-kazuho-h2-cache-digest/), avoiding duplicate push within same session, or other smarts.

---

Taking a step back, I'm not hearing any loud objections to the proposed description in this pull. 
1. I'll land proposed text as a starting point and we can refine it from there. 
2. I'll open a new pull request for ~nopush and we can hash out those details there.

**Comment by vkrasnov** [comment]
> The overhead of a PUSH_PROMISE is ~10~20 bytes

The overhead of a PUSH_PROMISE is at least the length of the url being pushed. Those tend to be very long sometimes.

> If we're delivering a large number of rel=preloads in the HEADERS frame, we're ~equally delaying the content TTFB.

I agree, and see no reason to pay the price twice per each asset.

**Comment by igrigorik** [comment]
> The overhead of a PUSH_PROMISE is at least the length of the url being pushed. Those tend to be very long sometimes.

Yes, but you have to send it either way: you're either sending it as a field within a HEADERS frame, or as a separate PUSH_PROMISE frame. The byte delta between those two is small, relative to the URL itself.

**Comment by icing** [comment]
> @igrigorik I think this is fine, modulo one nuance... Current implementations of push in Chrome+FF do not commit the resource to HTTP cache until it is matched by a client request. Preload resources, on the other hand, are committed to HTTP cache, since they're 'client-initiated'. As such, pushing a preload request + stripping the header changes the behavior a bit... This is gray (unspecified) area, and something we should probably define more formally.

Ah, you misunderstood me. `preload` link headers on pushed resources are left intact, e.g. sent out, but do not trigger a server push in Apache. So, all should be fine.

Have implemented `nopush` link param in `trunk`. Keep me posted if anything changes.

**Pull request merged**
